version: "3.2"
services:
  apache:
    build: 
      context: ./docker/apache
      args:
        APACHE_VERSION: ${APACHE_VERSION}
    environment:
      - HTTPS_METHOD=noredirect
      - VirtualHost
    ports:
      - "8084:80"
    volumes:
      - /Users/rsmoke/chem_awards/:/Users/rsmoke/chem_awards/
    depends_on:
      - php
    networks:
      - frontend
      - backend
    container_name: apache
  php:
    build:
      context: ./docker/php
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - /Users/rsmoke/chem_awards/:/Users/rsmoke/chem_awards/
    container_name: php
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: whe02.lsa.umich.edu
    restart: always
    ports:
      - 8081:80
networks:
  frontend:
  backend:

